# Debug settings
DISPLAY_DEBUG_MESSAGES = True

# Marker settings
IDS_CORNER_MARKERS = [0,1,2,3]
ID_GOAL_MARKER = 4
ID_ROBOT_MARKER = 5

# Camera settings
CAMERA_ID = 0
ITERATIONS_MAP_CREATION = 50
ITERATIONS_REAL_TIME_DETECTION = 4

# Environment settings
w_cm = 29.7*4
h_cm = 21*4
w_px = 640
h_px = round(w_px * h_cm / w_cm)
NUMBER_OF_OBSTACLES = 2
ROBOT_SIZE = 25

# Global navigation settings
DIST_FROM_GOAL_THRESH = 5
ANGLE_THRESH = 0.2
NOMINAL_SPEED = 75
K_ANGLE = 200
K_TRAJ = 300
DIST_FROM_GOAL_THRESH_LOCAL = 75 # TO BE CHANGED

# Local navigation settings
DIST_THRESH_LOCAL = 100
NOMINAL_SPEED_LOCAL = 80
SPEED_GAIN_LOCAL = [2.5, 1.75, -1, -1.75, -2.5]
ANGLE_THRESH_LOCAL = 0.2
K_ANGLE_LOCAL = 25
K_OBSTACLE_LOCAL = 0.016
LOCAL_AVOIDANCE_DELAY = 1.2

# Kidnapping settings
KIDNAPPING_CONV_THRESH = 4
KIDNAPPING_THRESH = 50
SLEEP_TIME_AFTER_KIDNAPPING = 5